packages:
  - apps/*
  - packages/*

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  "@scarf/scarf": false
  argon2: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true

overrides:
  deepmerge-ts: 8.0.1
  js-yaml: 5.3.0
  nanoid: 3.3.18
  postcss: 8.5.26
  sharp: 0.35.3
