export const RISK_ENGINE_CONSTANTS = {
  MINIMUM_REWARD_TO_RISK_RATIO: 2.5,
  MINIMUM_CONFIDENCE_THRESHOLD: 75,
  DEFAULT_PRECISION_DIGITS: 8,
  POSITION_SIZE_PRECISION_DIGITS: 12,
  EXPOSURE_TOLERANCE_EPSILON: 1e-9,
  RISK_SCORE_CATEGORY_WEIGHT: 25,
} as const;
