"""Core domain entities for trading signals."""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal

from src.core.domain.value_objects.enums import (
    SignalDirection,
    SignalStrength,
    Timeframe,
)


@dataclass(frozen=True)
class TradingSignal:
    """A trading signal generated by a strategy or AI analysis.

    Attributes:
        id: Unique signal identifier (UUID).
        symbol: Trading pair symbol.
        direction: Long, short, or neutral.
        strength: Signal confidence level.
        timeframe: Analysis timeframe.
        entry_price: Suggested entry price.
        stop_loss_price: Suggested stop-loss price.
        take_profit_price: Suggested take-profit price.
        confidence_score: Numeric confidence 0.0–1.0.
        source: Signal source identifier (strategy name, model, etc.).
        reasoning: Human-readable explanation of the signal.
        technical_indicators: Key technical indicator values.
        ai_analysis_id: Reference to the AI analysis that generated this.
        created_at: Signal generation timestamp (UTC).
        expires_at: Signal expiry timestamp (UTC).
    """

    symbol: str
    direction: SignalDirection
    strength: SignalStrength
    timeframe: Timeframe
    entry_price: Decimal
    stop_loss_price: Decimal
    take_profit_price: Decimal
    confidence_score: float
    source: str
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    reasoning: str = ""
    technical_indicators: dict[str, float] = field(default_factory=dict)
    ai_analysis_id: str | None = None
    created_at: datetime = field(default_factory=datetime.utcnow)
    expires_at: datetime | None = None

    def __post_init__(self) -> None:
        """Validate signal invariants."""
        if not (0.0 <= self.confidence_score <= 1.0):
            raise ValueError("Confidence score must be between 0.0 and 1.0")
        if self.entry_price <= Decimal("0"):
            raise ValueError("Entry price must be positive")
        if self.stop_loss_price <= Decimal("0") or self.take_profit_price <= Decimal("0"):
            raise ValueError("Stop loss and take profit must be positive")

    @property
    def risk_reward_ratio(self) -> Decimal:
        """Calculate risk-to-reward ratio."""
        if self.direction == SignalDirection.LONG:
            risk = self.entry_price - self.stop_loss_price
            reward = self.take_profit_price - self.entry_price
        elif self.direction == SignalDirection.SHORT:
            risk = self.stop_loss_price - self.entry_price
            reward = self.entry_price - self.take_profit_price
        else:
            return Decimal("0")

        if risk <= Decimal("0"):
            return Decimal("0")
        return reward / risk

    @property
    def is_expired(self) -> bool:
        """Check if the signal has expired."""
        if self.expires_at is None:
            return False
        return datetime.utcnow() > self.expires_at

    @property
    def is_actionable(self) -> bool:
        """Check if the signal is valid and not expired."""
        return (
            self.direction != SignalDirection.NEUTRAL
            and not self.is_expired
            and self.confidence_score >= 0.6
        )
