ALTER TYPE "EvaluationHorizon" ADD VALUE IF NOT EXISTS 'M15';
ALTER TYPE "EvaluationHorizon" ADD VALUE IF NOT EXISTS 'M30';
ALTER TYPE "EvaluationHorizon" ADD VALUE IF NOT EXISTS 'H2';
ALTER TYPE "EvaluationHorizon" ADD VALUE IF NOT EXISTS 'H4';

ALTER TABLE "performance_records"
  ADD COLUMN "strategyKey" TEXT,
  ADD COLUMN "leverage" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "netRoePct" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "leverageSource" TEXT NOT NULL DEFAULT 'UNLEVERAGED';
