export enum MarketStreamState {
  DISABLED = "DISABLED",
  CONNECTING = "CONNECTING",
  CONNECTED = "CONNECTED",
  DEGRADED = "DEGRADED",
  STALE = "STALE",
  RECONNECTING = "RECONNECTING",
  DISCONNECTED = "DISCONNECTED",
  FAILED = "FAILED",
}

export enum MarketEventType {
  TICKER_UPDATED = "TICKER_UPDATED",
  CANDLE_UPDATED = "CANDLE_UPDATED",
  CANDLE_CLOSED = "CANDLE_CLOSED",
  PUBLIC_TRADE_RECEIVED = "PUBLIC_TRADE_RECEIVED",
  ORDER_BOOK_UPDATED = "ORDER_BOOK_UPDATED",
  FUNDING_RATE_UPDATED = "FUNDING_RATE_UPDATED",
  OPEN_INTEREST_UPDATED = "OPEN_INTEREST_UPDATED",
  STREAM_CONNECTED = "STREAM_CONNECTED",
  STREAM_DISCONNECTED = "STREAM_DISCONNECTED",
  STREAM_STALE = "STREAM_STALE",
  STREAM_RECOVERED = "STREAM_RECOVERED",
  DATA_GAP_DETECTED = "DATA_GAP_DETECTED",
}

export enum IndicatorStatus {
  CLOSED = "CLOSED",
  PROVISIONAL = "PROVISIONAL",
  INSUFFICIENT_DATA = "INSUFFICIENT_DATA",
}

export enum DataGapStatus {
  DETECTED = "DETECTED",
  REPAIRING = "REPAIRING",
  REPAIRED = "REPAIRED",
  FAILED = "FAILED",
  IGNORED = "IGNORED",
}

export enum MarketIncidentCode {
  MALFORMED_PAYLOAD = "MALFORMED_PAYLOAD",
  INVALID_TIMESTAMP = "INVALID_TIMESTAMP",
  DUPLICATE_EVENT = "DUPLICATE_EVENT",
  OUT_OF_ORDER_EVENT = "OUT_OF_ORDER_EVENT",
  CANDLE_GAP = "CANDLE_GAP",
  ORDER_BOOK_SEQUENCE_GAP = "ORDER_BOOK_SEQUENCE_GAP",
  CROSSED_ORDER_BOOK = "CROSSED_ORDER_BOOK",
  STREAM_STALE = "STREAM_STALE",
  STREAM_DISCONNECTED = "STREAM_DISCONNECTED",
  PROVIDER_RATE_LIMIT = "PROVIDER_RATE_LIMIT",
  PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE",
}
