export const API_ENDPOINTS = {
  auth: {
    me: "/auth/me",
    login: "/auth/login",
    logout: "/auth/logout",
    register: "/auth/register",
    resendVerification: "/auth/resend-verification",
    verifyEmail: "/auth/verify-email",
    resetPassword: "/auth/reset-password",
    changePassword: "/auth/change-password",
    sessions: "/auth/sessions",
    sessionsById: (id: string) => `/auth/sessions/${id}`,
    totpSetup: "/auth/totp/setup",
    totpConfirm: "/auth/totp/confirm",
    totpDisable: "/auth/totp/disable",
    reauthenticate: "/auth/reauthenticate",
  },
  settings: "/settings",
  credentials: {
    root: "/credentials",
    byId: (id: string) => `/credentials/${id}`,
    test: (id: string) => `/credentials/${id}/test`,
  },
  exchangeConnections: {
    root: "/exchange-connections",
    byId: (id: string) => `/exchange-connections/${id}`,
    test: (id: string) => `/exchange-connections/${id}/test`,
    account: (id: string) => `/exchange-connections/${id}/account`,
    balances: (id: string) => `/exchange-connections/${id}/balances`,
    positions: (id: string) => `/exchange-connections/${id}/positions`,
    openOrders: (id: string) => `/exchange-connections/${id}/orders/open`,
    enable: (id: string) => `/exchange-connections/${id}/enable`,
    disable: (id: string) => `/exchange-connections/${id}/disable`,
  },
  ai: {
    providers: "/ai/providers",
    models: "/ai/models",
    config: "/ai/config",
    usage: "/ai/usage",
    history: (limit = 30) => `/ai/history?limit=${limit}`,
    test: "/ai/test",
    chatStream: "/ai/chat/stream",
    tools: "/ai/tools",
    toolsHealth: "/ai/tools/health",
    toolsHistory: "/ai/tools/history",
    agents: "/ai/agents",
    agentsHealth: "/ai/agents/health",
    agentRun: (id: string) => `/ai/agents/${id}`,
    systemDiagnosticRun: "/ai/agents/system-diagnostic/run",
    decision: "/ai/decision",
    analysisRun: (agentType: string) => `/agents/${agentType}/runs`,
    liveTrading: "/ai/live-trading",
    liveTradingSync: "/ai/live-trading/sync",
    liveTradingKillSwitch: "/ai/live-trading/kill-switch",
    liveTradingEnable: "/ai/live-trading/kill-switch/enable",
    performanceMetrics: "/ai/performance/metrics",
    performanceRoot: "/ai/performance",
    performanceAlerts: "/ai/performance/alerts",
    portfolio: "/ai/portfolio",
    portfolioRebalance: "/ai/portfolio/rebalance",
    portfolioStrategyStatus: (key: string) => `/ai/portfolio/strategies/${key}/status`,
    reflection: "/ai/reflection",
    reflectionInsights: "/ai/reflection/insights",
    reflectionProposals: "/ai/reflection/proposals",
    reflectionRun: "/ai/reflection/run",
    risk: "/ai/risk",
  },
  pipeline: {
    health: "/system/pipeline/health",
    schedules: "/pipeline/schedules",
    byId: (id: string) => `/pipeline/schedules/${id}`,
    run: "/pipeline/run",
  },
  pipelineRuns: {
    root: "/pipeline-runs",
    byId: (id: string) => `/pipeline-runs/${id}`,
    replay: (id: string) => `/pipeline-runs/${id}/replay`,
    cancel: (id: string) => `/pipeline-runs/${id}/cancel`,
  },
  externalData: {
    newsList: "/external-data/news",
    newsDetail: (id: string) => `/external-data/news/${id}`,
    newsSave: (id: string) => `/external-data/news/${id}/save`,
    newsRead: (id: string) => `/external-data/news/${id}/read`,
    sources: "/external-data/sources",
    sourceById: (id: string) => `/external-data/sources/${id}`,
    sourceTest: (id: string) => `/external-data/sources/${id}/test`,
    socialProviders: "/external-data/social/providers",
    providersHealth: "/external-data/providers/health",
    providerRun: (providerId: string) => `/external-data/providers/${providerId}/run`,
    macroEvents: "/external-data/macro/events",
    macroImportPreview: "/external-data/macro/import/preview",
    macroImport: "/external-data/macro/import",
    sentiment: "/external-data/sentiment",
    sentimentHistory: "/external-data/sentiment/history",
  },
  quant: {
    recommendations: "/quant-intelligence/recommendations",
    recommendationReview: (id: string) => `/quant-intelligence/recommendations/${id}/review`,
  },
  agentRuns: {
    root: "/agent-runs",
    byId: (id: string) => `/agent-runs/${id}`,
    transitions: (id: string) => `/agent-runs/${id}/transitions`,
    cancel: (id: string) => `/agent-runs/${id}/cancel`,
  },
} as const;
