export const ROUTES = {
  home: "/",
  market: "/market",
  login: "/login",
  profile: "/profile",
  register: "/register",
  forgotPassword: "/forgot-password",
  verifyEmail: "/verify-email",
  resetPassword: "/reset-password",
  settings: "/settings",
  settingsExchanges: "/settings/exchanges",
  settingsExchangeDetail: (id: string) => `/settings/exchanges/${id}`,
  settingsAi: "/settings/ai",
  settingsAiTools: "/settings/ai/tools",
  dataSource: "/settings/data-sources",
  ai: {
    root: "/ai",
    decision: "/ai/decision",
    pipeline: "/ai/pipeline",
    pipelineRuns: "/ai/pipeline-runs",
    pipelineRunDetail: (id: string) => `/ai/pipeline-runs/${id}`,
    liveTrading: "/ai/live-trading",
    portfolio: "/ai/portfolio",
    agents: "/ai/agents",
    agentRuns: "/ai/agent-runs",
    agentRunDetail: (id: string) => `/ai/agent-runs/${id}`,
    reflection: "/ai/reflection",
    performance: "/ai/performance",
  },
  apiKeys: "/api-keys",
  security: "/security",
  recommendations: "/recommendations",
  news: "/news",
  newsDetail: (id: string) => `/news/${id}`,
  sentiment: "/sentiment",
  systemProviders: "/system/providers",
} as const;
