export const ROUTES = {
  home: "/",
  market: "/market",
  login: "/login",
  profile: "/profile",
  register: "/register",
  forgotPassword: "/forgot-password",
  verifyEmail: "/verify-email",
  resetPassword: "/reset-password",
  settings: "/settings",
  settingsExchanges: "/settings/exchanges",
  settingsExchangeDetail: (id: string) => `/settings/exchanges/${id}`,
  settingsAi: "/settings/ai",
  settingsAiTools: "/settings/ai/tools",
  dataSource: "/settings/data-sources",
  liveTrading: "/live-trading",
  quantIntelligence: "/quant-intelligence",
  research: "/research",
  factors: "/factors",
  strategyLab: "/strategy-lab",
  portfolioIntelligence: "/portfolio-intelligence",
  recommendations: "/recommendations",
  knowledge: "/knowledge",
  news: "/news",
  newsDetail: (id: string) => `/news/${id}`,
  macro: "/macro",
  sentiment: "/sentiment",
  systemProviders: "/system/providers",
  apiKeys: "/api-keys",
  security: "/security",
  ai: {
    root: "/ai",
    decision: "/ai/decision",
    pipeline: "/ai/pipeline",
    pipelineRuns: "/ai/pipeline-runs",
    pipelineRunDetail: (id: string) => `/ai/pipeline-runs/${id}`,
    liveTrading: "/live-trading",
    portfolio: "/ai/portfolio",
    agents: "/ai/agents",
    diagnostic: "/ai/agents/diagnostic",
    agentRuns: "/ai/agent-runs",
    agentRunDetail: (id: string) => `/ai/agent-runs/${id}`,
    reflection: "/ai/reflection",
    performance: "/ai/performance",
    risk: "/ai/risk",
    marketAnalysis: "/ai/market-analysis",
    technicalAnalysis: "/ai/technical-analysis",
    newsAnalysis: "/ai/news-analysis",
    sentimentAnalysis: "/ai/sentiment-analysis",
  },
} as const;
