export enum AgentInvocationSource {
  USER_MANUAL = 'USER_MANUAL',
  INTERNAL_SERVICE = 'INTERNAL_SERVICE',
  SYSTEM_TEST = 'SYSTEM_TEST',
  REPLAY = 'REPLAY',
  FUTURE_SCHEDULED = 'FUTURE_SCHEDULED',
  FUTURE_EVENT_DRIVEN = 'FUTURE_EVENT_DRIVEN'
}
