export enum AgentType {
  MARKET_ANALYST = 'MARKET_ANALYST',
  TECHNICAL_ANALYST = 'TECHNICAL_ANALYST',
  NEWS_ANALYST = 'NEWS_ANALYST',
  SOCIAL_ANALYST = 'SOCIAL_ANALYST',
  MACRO_ANALYST = 'MACRO_ANALYST',
  ON_CHAIN_ANALYST = 'ON_CHAIN_ANALYST',
  RISK_REVIEWER = 'RISK_REVIEWER',
  DECISION_SYNTHESIZER = 'DECISION_SYNTHESIZER',
  JUDGE = 'JUDGE',
  MEMORY = 'MEMORY',
  PERFORMANCE = 'PERFORMANCE',
  REFLECTION = 'REFLECTION',
  SYSTEM_DIAGNOSTIC = 'SYSTEM_DIAGNOSTIC'
}
