export enum AgentContextSection {
  MARKET_TICKER = 'MARKET_TICKER',
  MARKET_CANDLES = 'MARKET_CANDLES',
  MARKET_INDICATORS = 'MARKET_INDICATORS',
  MARKET_FUNDING = 'MARKET_FUNDING',
  MARKET_OPEN_INTEREST = 'MARKET_OPEN_INTEREST',
  MARKET_ORDER_BOOK = 'MARKET_ORDER_BOOK',
  NEWS = 'NEWS',
  SENTIMENT = 'SENTIMENT',
  SOCIAL = 'SOCIAL',
  MACRO = 'MACRO',
  USER_SETTINGS = 'USER_SETTINGS',
  AI_CONFIG = 'AI_CONFIG',
  EXCHANGE_ACCOUNT_SUMMARY = 'EXCHANGE_ACCOUNT_SUMMARY',
  OPEN_POSITIONS = 'OPEN_POSITIONS',
  MEMORY = 'MEMORY',
  PREVIOUS_AGENT_RESULTS = 'PREVIOUS_AGENT_RESULTS'
}
